fn p384_scalar_inv_to_mont(a: Scalar<R>, cpu: cpu::Features) -> Scalar<R> {
    // Fermat: a**-1 (mod n) == a**(n - 2) (mod n).
    // Addition chain: 422 = 382 squarings + 40 multiplications (research/p384-422, generated by tools/p384chain.py).

    // mul, sqr, sqr_mut, sqr_mul, sqr_mul_acc: unchanged from ring (see src/ec/suite_b/ops/p384.rs).

    const B_1: usize = 0; // 1
    const B_11: usize = 1; // 3
    const B_11000011: usize = 2; // 195
    const B_11000011011: usize = 3; // 1563
    const B_11011011011: usize = 4; // 1755
    const B_11110011011: usize = 5; // 1947
    const B_100111100111: usize = 6; // 2535
    const B_100111101001: usize = 7; // 2537
    const B_111111111111: usize = 8; // 4095
    const DIGIT_COUNT: usize = 9;

    let mut d = [Scalar::zero(); DIGIT_COUNT];
    d[B_1] = a;
    let b_10 = &sqr(&d[B_1], cpu); // 2
    d[B_11] = mul(b_10, &d[B_1], cpu); // 3
    let b_110 = &sqr(&d[B_11], cpu); // 6
    let b_1100 = &sqr(b_110, cpu); // 12
    let b_11000 = &sqr(b_1100, cpu); // 24
    let b_110000 = &sqr(b_11000, cpu); // 48
    let b_1100000 = &sqr(b_110000, cpu); // 96
    let b_11000000 = &sqr(b_1100000, cpu); // 192
    d[B_11000011] = mul(b_11000000, &d[B_11], cpu); // 195
    let b_110000110 = &sqr(&d[B_11000011], cpu); // 390
    let b_1100001100 = &sqr(b_110000110, cpu); // 780
    let b_11000011000 = &sqr(b_1100001100, cpu); // 1560
    d[B_11000011011] = mul(b_11000011000, &d[B_11], cpu); // 1563
    d[B_11011011011] = mul(&d[B_11000011011], b_11000000, cpu); // 1755
    d[B_11110011011] = mul(&d[B_11011011011], b_11000000, cpu); // 1947
    d[B_100111100111] = mul(&d[B_11011011011], b_1100001100, cpu); // 2535
    d[B_100111101001] = mul(&d[B_100111100111], b_10, cpu); // 2537
    d[B_111111111111] = mul(&d[B_100111100111], b_11000011000, cpu); // 4095
    let x24 = &sqr_mul(&d[B_111111111111], 12, &d[B_111111111111], cpu); // 2^24 - 1
    let x48 = &sqr_mul(x24, 24, x24, cpu); // 2^48 - 1
    let x96 = &sqr_mul(x48, 48, x48, cpu); // 2^96 - 1
    let mut acc = sqr_mul(x96, 96, x96, cpu); // 2^192 - 1

    // Low 192 bits of n - 2: (squarings, digit) windows, left to right.
    #[allow(clippy::cast_possible_truncation)]
    static REMAINING_WINDOWS: [(u8, u8); 28] = [
        (6, B_1 as u8),
        (5, B_11000011011 as u8),
        (14, B_11000011011 as u8),
        (5, B_111111111111 as u8),
        (11, B_100111100111 as u8),
        (3, B_111111111111 as u8),
        (7, B_11000011011 as u8),
        (6, B_11110011011 as u8),
        (3, B_1 as u8),
        (9, B_100111101001 as u8),
        (8, B_11 as u8),
        (3, B_111111111111 as u8),
        (9, B_11000011011 as u8),
        (9, B_11000011 as u8),
        (8, B_11000011011 as u8),
        (8, B_11110011011 as u8),
        (6, B_100111100111 as u8),
        (12, B_11110011011 as u8),
        (7, B_100111100111 as u8),
        (3, B_11 as u8),
        (16, B_11000011011 as u8),
        (5, B_11011011011 as u8),
        (4, B_111111111111 as u8),
        (2, B_11011011011 as u8),
        (10, B_100111101001 as u8),
        (6, B_111111111111 as u8),
        (4, B_1 as u8),
        (3, B_100111101001 as u8),
    ];
    for &(squarings, digit) in &REMAINING_WINDOWS[..] {
        sqr_mul_acc(&mut acc, LeakyWord::from(squarings), &d[usize::from(digit)], cpu);
    }

    acc
}
